- docker-compose.yml
Enterprise installation wasn't working using the 7.0 image. 
The setup script included in that image doesn't support the `M2SETUP_USE_COMPOSER_ENTERPRISE` variable.
Looking at the image used for phpfpm, it seems like the setup one should have been bumped too?
> Fixed setup image version, Enterprise installation support

- README.md
- lib/template
Currently, the installation process fails when a user hasn't yet set up their GitHub account or an SSH public key.
Using the `https://` URL prevents things from failing.
> allow setup without ssh credentials

- compose/magento-2-windows/bin/copydir.ps1
- compose/magento-2/bin/copyfromcontainer
- compose/magento-2/bin/copytocontainer
> FYI, I came across this issue using the [mage2click/docker-magento-mutagen](https://github.com/mage2click/docker-magento-mutagen) project which is based off of this project. I submitted the same PR there: https://github.com/mage2click/docker-magento-mutagen/pull/20
When using the `bin` scripts I noticed that sometimes the commands worked and sometimes they would throw an error like this: 
```
Error: No such container:path: magento-231_phpfpm_1:/var/www/html/auth.json
```
In this situation, my directory name is `docker-magento-231` and the container's name is `docker-magento-231_phpfpm_1`. Weirdly enough anything from the first `-` and before is being omitted from the docker commands. I found that the width of the terminal window was actually affecting this. 
**Example**
If the window …
> Use container id for docker commands

- compose/magento-2/bin/setup
I fixed setup script where is used n98-magerun2 without .phar extension.
In bin/n98-magerun2 file is call:
#!/bin/bash
bin/cli bin/n98-magerun2.phar "$@"
and it didn't work when we had saved magerun script: src/bin/n98-magerun
> Fix Magento2 setup script with n98-magerun2.phar

- compose/magento-2/bin/dev-urn-catalog-generate
Fix dev-urn-catalog-generate :
Restore the sed replace and made it globally (some <resource> are multiline)
Works if src is a symlink
> Fix dev-urn-catalog-generate

- compose/magento-2/bin/copyfromcontainer
- compose/magento-2/bin/copytocontainer
The fix concerns both bin/copyfromcontainer and bin/copytocontainer to allow 'src' being a symlink.
Actually, docker cp fails on copying files on symlink.
The fix consists in resolving "real path" to 'src' to make docker cp.
I choose cd + pwd for Mac OSX compliance.
> Allow 'src' being a symlink to actual directory of Magento project on disk

- images/php/7.2/Dockerfile
For some reason, the image `7.2-fpm-7` is missing ioncube loader, because it fails to move the file (directory not empty when using the wildcard * character).
```
[razvan@avramescu-net new]$ docker run -ti markoshust/magento-php:7.2-fpm-7 bash
app@49915c118de1:~/html$ ls -alh /usr/local/lib/php/extensions 
total 12K
drwxr-xr-x. 1 root root 4.0K Jan 24 09:28 .
drwxr-xr-x. 1 root root 4.0K Jan 24 09:28 ..
drwxr-xr-x. 1 root root 4.0K Feb  1 01:37 no-debug-non-zts-20170718
```
The change should do the trick. It could also be fixed by just removing the wildcard character.
> PHP 7.2-fpm-7 missing ioncube .so file FIX

- compose/bin/removevolumes
Since docker uses lower case volume names, make sure to convert the current directory to lowercase before passing it to the docker command.
> Make sure directory name is converted to lowercase

- images/php/7.2/Dockerfile
- images/php/7.3/Dockerfile
For php7.2 this path of php-ext is changed:
/usr/local/lib/php/extensions/no-debug-non-zts-20151012/ioncube_loader_lin_7.2.so
/usr/local/lib/php/extensions/no-debug-non-zts-2017XXXX/ioncube_loader_lin_7.2.so
Also add ioncube for php 7.3
Its commit will work normally when path changes again in the future.
> Add ioncube-loader for php 7.2 and 7.3 Dockerfile

- compose/bin/mysql
Just a quick bin script I am using locally to connect to mysql via the `bin/cli` command
While using your setup I have found it useful to connect to the DB to check some stuff via the command line. Maybe most people will use another client but for me, I like the CLI.
It would be cool to load in the user/password/host etc but I am not too sure how to do this. If you know and let me know I would be happy to update this for you here.
> Add new new cli to connect to the mysql system

- README.md
- compose/bin/remove
- compose/bin/removeall
- compose/bin/removevolumes
- compose/bin/status
After discussion #236 and modified this pull
1. Added `bin/removeall` for removing all containers, networks, volumes, and images.
2. Fixed docker-compose issue, it should include docker-compose.yml and docker-compose.dev.yml 
3. `bin/remove`: Add `--stop` param that stop containers first and remove stoped containers
4. Keep `bin/removevolumes` and fixed volume naming rule.
5. Updated README.md
PS: 
Because `bin/removevolumes` action is removing volume only, it will need to maintain in the future when volume setting changing in docker-compose.yml.
The `docker-compose down` is inappropriate because it [default action](https://docs.docker.com/compose/reference/down/) is removing containers and networks
> Added bin/removeall and fixed few issues

- compose/bin/copyfromcontainer
Tested with:
For files:
```
bin/cli touch dev/tests/test-file2.txt
bin/copyfromcontainer dev/tests/test-file2.txt
ls -la src/dev/tests/test-file2.txt
```
For directories:
```
bin/cli mkdir -p dev/test-dir
bin/cli touch dev/test-dir/test-file1.txt
bin/cli touch dev/test-dir/test-file2.txt
bin/copyfromcontainer dev/test-dir
ls -la src/dev/test-dir
```
Previous result for above was:
```
bin/copyfromcontainer dev/test-dir
Completed copying dev/test-dir from container to host
ls -la src/dev/test-dir
ls: cannot access 'src/dev/test-dir': No such file or directory
ls -la src/test-dir
total 8
drwxrwxr-x  2 piotr piotr 4096 Aug  8 19:45 .
drwxrwxr-x 17 piotr piotr 4096 Aug  8 22:06 ..
-rw-rw-r--  1 piotr piotr    0 Aug  8 19:45 test-file1.txt
-rw-rw-r--  1 piotr piotr    0 Aug  8 19:45 …
```
> improve nested file and directory support for copyfromcontainer

- compose/bin/copytocontainer
Tested with:
For files:
```
touch src/dev/tests/test-file2.txt
bin/copytocontainer dev/tests/test-file2.txt
bin/cli ls dev/tests/test-file2.txt
```
For directories:
```
mkdir -p src/dev/test-dir
touch src/dev/test-dir/test-file1.txt
touch src/dev/test-dir/test-file2.txt
bin/copytocontainer dev/test-dir
bin/cli ls -la dev/test-dir
```
Previous result for above was:
```
bin/copytocontainer dev/test-dir
Completed copying dev/test-dir from host to container
Correcting filesystem ownerships...
chown: cannot access '/var/www/html/dev/test-dir': No such file or directory
Filesystem ownerships corrected.
Correcting filesystem permissions...
find: 'dev/test-dir': No such file or directory
find: 'dev/test-dir': No such file or directory
Filesystem permissions corrected.
```
After the change:
``` …
```
> Handle nested files in copytocontainer script

- images/php/7.3/Dockerfile
- images/php/7.4/Dockerfile
Install `ps` command on the php container to eliminate while running integration tests:
```
Fatal error: Uncaught Exception: sh: 1: tasklist.exe: not found in /var/www/html/vendor/magento/framework/Shell.php:63
```
It's not a fault of the memory check command in magento core. It's more a workaround for now if you're happy to merge.
Reference in core: https://github.com/magento/magento2/blob/2.4-develop/dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php#L49-L61
I hope to have some time next week to see if I can fix that in core. Anyway it'll take some time to be released even if fix is merged.
`ps` can also be installed manually using:
```
bin/root apt update
bin/root apt install procps
```
> add ps command to eliminate exception while running integration tests

- compose/bin/setup
- compose/bin/start
1. Increase the seconds to ensure containers are started
2. Add volume files validator for `bin/start`. Avoiding to generate useless empty folder when there is a lack of volume files. ex: `./src/composer.json`, `./src/composer.lock`, and `./src/nginx.conf.sample`
> Add checker for docker-compose up

- README.md
- compose/bin/dbdump
- compose/bin/mysql
- compose/bin/n98-magerun2
- compose/env/db.env
1. Update Magento Default version in `lib/onelinesetup`
2. Add `bin/dbdump` to export database.
3. Add `MYSQL_HOST=db` in `env/db.env`. It's only used for this project's bin tools. It's not for environment variables of the percona:5.7 image.
4. Improve `bin/mysql` to detect stdin to use tty or notty
5. Modify `bin/n98-magerun2` for 2 space indent
6. Update `REAME.md`. I have the least confidence for this part ...
> Add bin/dbdump and improve bin/mysql

- compose/bin/start
fixes #309
```
substr(string, start [, length ])
If start is less than one, substr() treats it as if it was one. (POSIX doesn’t specify what to do in this case: BWK awk acts this way, and therefore gawk does too.) If start is greater than the number of characters in the string, substr() returns the null string. Similarly, if length is present but less than or equal to zero, the null string is returned.
```
Apparently Ubuntu 18.04 had an older version of awk which didn't handle above the same way.
> fix start script on ubuntu 18.04

- compose/bin/setup
Refs: #283
@rangerz tips for setup.
Tested after running bin/setup:
```
Recreating compose_phpfpm_1      ... done
Recreating compose_app_1         ... done
Docker development environment setup complete.
You may now access your Magento instance at https://magento2.test/
#:~/projects/dm-redis/compose (master) $ bin/redis redis-cli monitor
OK
1598896103.038085 [0 192.168.80.7:59066] "select" "1"
1598896103.044390 [0 192.168.80.7:59068] "hget" "zc:k:69d_GLOBAL__DICONFIG" "d"
1598896103.057593 [0 192.168.80.7:59068] "hget" "zc:k:69d_DICONFIG70F9A356A11A3AEF67B14BCEDECB0F36" "d"
1598896103.062639 [0 192.168.80.7:59068] "hget" "zc:k:69d_INTERCEPTION" "d"
1598896103.074890 [0 192.168.80.7:59070] "select" "1"
```
> enable redis during setup, set backend base to admin, https for unsecure

- compose/docker-compose.yml
Refs: #244
Use official alpine images for redis and rabbitmq. It haves about 30-40mb.
Mailhog already uses alpine.
Later I'll see if I can do something about phpfrm or nginx. It's a quick win in meantime.
> use alpine image for redis and rabbitmq

- compose/bin/restart
- compose/bin/start
- compose/bin/stop
- compose/bin/xdebug
Added a bypass for start/stop/restart to allow rerunning selected service to restart just phpfpm after toggling xdebug.
> restart only phpfpm to toggle xdebug, rerun of selected service

- compose/bin/fixperms
instead of one by one
Old:
```
Correcting filesystem permissions...
Filesystem permissions corrected.
real	1m54.605s
user	0m1.414s
sys	0m0.316s
```
New:
```
Correcting filesystem permissions...
Filesystem permissions corrected.
real	0m3.418s
user	0m0.945s
sys	0m0.231s
```
You can change `chmod` to `echo` to see the difference in the returned output. 
All paths are passed in one go to chmod instead of running it one by one on each file.
Similar command is used now in Magento 2 docs: https://devdocs.magento.com/guides/v2.4/config-guide/prod/prod_file-sys-perms.html#Production-file-system-ownership-for-shared-hosting-one-user-
> Optimize fixperms by using one find loop and passing all paths in one go

- compose/bin/setup
- compose/bin/setup-composer-auth
`setup-composer-auth` can setup `~/.composer/auth.json` for using composer in `docker-compose.yml`
```
volumes: &appvolumes
- ~/.composer:/var/www/.composer:cached
```
The auth setting can from `~/src/auth.json` or manual input, and can use `composer` or `python3` on host
> Add setup-composer-auth

- compose/bin/setup-ssl
- compose/bin/setup-ssl-ca
In bin/setup-ssl 
There is no CA file to read  in order to call bin/setup-ssl-ca. You must create it first.
In bin/setup-ssl-ca
The `mkcert -install` is in the wrong place, the statement will never be reached unless the CA is already there.
> mkcert -install is being called in the wrong place

- compose/bin/xdebug
This is for lazy ones.. 
Now you can use `bin/xdebug en`, `bin/xdebug dis` or any other thing that starts with `d` or `e` to disable or enable xdebug. :O
> Make xdebug command understand partials

- compose/bin/xdebug
I usually toggle xdebug on and off depending on what tasks I'm doing. Such as `bin/magento setup:upgrade`, usually chained with other stuff. Having xdebug enabled slows my fpm-container to a crawl. So being able to toggle xdebug, and see the current status of xdebug is kinda helpful.
> Extended functionality for bin/xdebug

- compose/bin/setup
There is no sense to continue installation process in case when Elasticsearch service isn't available. 
We will try to connect every 5 sec during next 30 sec. And script is stopped if it's unsuccessful.
This helps to prevent failed Magento installation in next cases:
1. Elasticsearch container is running, however Elasticsearch service isn't ready
2. Elasticsearch container was killed because of RAM issues.
So we can detect Elasticsearch issues on early stage.
Otherwise, we will see an error during installation:
`Could not validate a connection to Elasticsearch. No alive nodes found in your cluster`
> Check Elasticsearch connection before setup:install

- images/php/7.3/Dockerfile
- images/php/7.4/Dockerfile
- images/php/8.0/Dockerfile
I am using this awesome docker configuration for developing ScandiPWA theme for Magento 2.
And it requires node version higher than 12.x.x.
And also currently used node version (10) run to it's end of life ([2021-04-30](https://nodejs.org/en/about/releases/)) 
So, I'm proposing upgrade node version.
> Update nodejs to latest LTS

- .github/workflows/shellcheck.yml
- compose/bin/copyfromcontainer
- compose/bin/copytocontainer
- compose/bin/download
- compose/bin/mysql
- compose/bin/pwa-studio
- compose/bin/removevolumes
- compose/bin/setup
- compose/bin/setup-composer-auth
- compose/bin/setup-grunt
- compose/bin/setup-integration-tests
- compose/bin/setup-pwa-studio
- compose/bin/setup-ssl-ca
- compose/bin/start
- compose/bin/update
- compose/bin/xdebug
https://github.com/markshust/docker-magento/pull/387 but with Github Action
> shellcheck fix with github action

- compose/docker-compose.dev.yml
As mentioned by @vy-shmal [here](https://github.com/markshust/docker-magento/issues/405#issuecomment-776029611), if we comment nginx.conf line, we don't get Magento's nginx configuration, causing 403 error.
> Change in note for linux users

- compose/docker-compose.yml
- DB from Percona `5.7` to Maria DB `10.4` which has [multi-arch support](https://hub.docker.com/_/mariadb?tab=tags&page=1&ordering=last_updated&name=10.4)
Closes #499
> Replace Percona DB with MariaDB 10.4

- compose/bin/setup
The setup is ran within the container, so interaction is not possible.
To not block the setup, --no-interaction should be added.
For example, if an existing project with stores in the config.php get's installed with a clean database, Magento will ask if it should create those store views as well.
The no-interaction defaults to yes in this case.
> Update setup with no interaction

- compose/bin/setup-domain
Small patch to add the domain into _/etc/hosts_ only if it isn't already there
> fix: prevent /etc/hosts domain duplication

- lib/onelinesetup
Since we have new patch versions and the new stable version 2.4.4 working fine. I think it's relevant to update it.
What do you think? I can change it to p3 in case you don't want the lasted version as default.
> Magento 2.4.4 as default

- compose/bin/update
When calling `bin/update` the `rsync` call should only update actually changed files. Currently all files are overwritten because the files in `tmpupdate` will have newer timestamps. Thus disabling timestamp comparisons and adding checksumming. This shouldn't impact rsync performance since there are no large binaries in the repo. 
For more info see: https://stackoverflow.com/a/44353773/1238689
> bin/update: rsync ignore timestamp

- README.md
Adds a new section on the Readme file called Xdebug & VS Code in a WSL2 environment, which explains how to setup Xdebug in Windows OS, running WSL2.
This will fix the issue #623
> Updates Readme file with new info on configuring Xdebug in WSL2 environments

- compose/bin/start
This was causing issues if the volume mapped contained regex metacharacters, e.g. periods:
```sh
file='/src/p...hes'
file2='/src/patches'
IGNORE_LIST='/src/patches /src/foo'
[[ " $IGNORE_LIST " =~ $file ]] # returns true (shouldn't)
[[ " $IGNORE_LIST " =~ $file2 ]] # returns true
```
Included fix, using globs instead:
```sh
[[ " $IGNORE_LIST " = *" $file "* ]] # returns false
[[ " $IGNORE_LIST " = *" $file2 "* ]] # returns true
```
`= <glob>` is also safer than `=~ <regex>` with arbitrary user strings, but in this case, it's actually more correct.
> Fix user string interpreted as regex

- README.md
- compose/compose.yaml
Some of the changes required to successfully switch from using OpenSearch to Elasticsearch are undocumented. This has caused people issues so let's document the steps required to make the switch as easy as possible.
Ideally the change to the `bin/setup` script would not be required - instead detecting which search service you are using and using the appropriate `--elasticsearch-host` value during `setup:install`. Unfortunately I don't have the time to look into this at the moment so this might be the next best thing 🤷‍♂️ 
#829
> OpenSearch -> Elasticsearch Instructions

- compose/bin/removeall
Remove the need for manually stopping all containers before removing them when running `bin/removeall`.
Another opinionated change so input and discussion is welcome 🙂
> Stop Containers Before Removing

- compose/bin/setup-composer-auth
- compose/bin/setup-grunt
Changes to satisfy the spellchecker check. A recent pull request of mine (#835) reported errors due to inconsistencies in unrelated files. These changes are to resolve those. I've done this as a separate pull request as these changes are unrelated to the others in #835.
For reference, the reported errors were:
```
Notice: ./compose/bin/setup-composer-auth:14:6: note: Double quote to prevent globbing and word splitting. [SC2086]
Notice: ./compose/bin/setup-grunt:63:16: note: Double quote to prevent globbing and word splitting. [SC2086]
Notice: ./compose/bin/setup-grunt:64:16: note: Double quote to prevent globbing and word splitting. [SC2086]
```
> Satisfy Spell Checker

- README.md
Updates `bin/removeall` command description to inform people that it also calls `bin/stopall`. This should have been done as part of #837 .
> Update bin/removeall Documentation

- compose/bin/setup
Use `docker info -f` to get the number of bytes. This results in fewer dependencies on external programs, and better usage of Bash shell math.
Removes comment stemming from confusion about GiB vs GB. :-)
> Simplify RAM check

- compose/bin/setup
- compose/bin/setup-install
Sometimes we just need to run bin/magento setup:install script, so maybe it can be a better approach to divide the setup script to can use the setup-install command alone.
> Setup script is divided to 2 parts

- README.md
Moved the command "bin/mysqldump", since this is only available for a new "docker-magento" user after downloading the Docker Compose template.
> Changed sequence of commands

- compose/bin/setup-install
The usage of `--cleanup-database` helps to finish the installation in most of cases, avoiding small fixable issues during clean installations and installations with pre-created databases as well.
> Update setup-install to cleanup

- compose/bin/copyfromcontainer
It creates the src folder when copying all the code from the repo first the first time, by the src doesn't exist. 
An example is when the dev follows the README part saying to run bin/cli git clone .... to start the project.
> Update copyfromcontainer to create src folder

- compose/template/dev/tests/integration/etc/install-config-mysql.php.2.3.dist
- compose/template/dev/tests/integration/etc/install-config-mysql.php.2.4.dist
When running the integration tests, it fails to connect to RabbitMQ because the pre-made integration tests configuration templates contain different RabbitMQ login credentials than are in rabbitmq.env.
This pull request modifies the templates to contain the same values as the default rabbitmq.env values
> Modify RabbitMQ credentials in test templates to comply with rabbitmq.env

- README.md
- compose/compose.yaml
- compose/env/cloudflare.env
This MR adds support for Cloudflare Tunnels (https://www.cloudflare.com/products/tunnel/).
This is helpful when you need your instance to have public domain, so you can allowlist it with 3-p services that don't allow connections from localhost.
**Added:**
- Main config update (commented Cloudflare Tunnel section)
- Env file for Cloudflare to include your tunnel's token
- Update to Readme to cover setup part
**NOTE:** Cloudflare Tunnel makes app visible to the world, so use it carefully to not leave Magento instance always available publicly.
> Add Optional Support for Cloudflare Tunnels

- compose/bin/docker-compose
This is the first step to allow more flexibility.
For example instead of having blackfire commented out in main compose.yaml.
It could be moved to a separate file and included in the list when feature toggle is enabled.
Something like:
```
if [ ${BLACKFIRE_ENABLED} -eq 1 ]; then
COMPOSE_FILES_LIST+=("compose.blackfire.yaml")
fi
```
It would allow adding features like https://github.com/markshust/docker-magento/pull/998 the same way.
> rework docker compose script to allow future extensibility

- README.md
I followed the directions when I tried to set up Magento, but when I ran the bin/setup script, I encountered the following issue:
"Could not validate a connection to Elasticsearch. No alive nodes found in your cluster", and I noticed a mistake in the README.md file, which this PR corrects.
> Fix elasticsearch host and port

- .github/dependabot.yml
This should help with keeping github actions up to date.
This should resolve https://github.com/markshust/docker-magento/issues/839
> add dependabot to update github actions

- compose/bin/download
Users frequently encounter the "Project directory "/var/www/html/." is not empty" error during installation, leading to numerous GitHub issues.
Implemented a detection mechanism during bin/download to identify the presence of the errors. The message guides them to refer to [this link](https://github.com/markshust/docker-magento#install-fails-because-project-directory-is-not-empty) on GitHub for more information on resolving the [issue](https://github.com/markshust/docker-magento/issues/823).
The prompt aims to improve user experience by proactively addressing common installation challenges.
The provided link contains detailed information on troubleshooting and resolving the specified errors.
> Show a message to the user that they have a failed install

- images/php/8.1/Dockerfile
- images/php/8.2/Dockerfile
This PR adds support for strace to the PHP 8.2/8.1 Docker image. The strace tool is included to help troubleshoot potential issues related to consumers running out of control, as outlined in the [GitHub issue](https://github.com/markshust/docker-magento/issues/983).
> Add strace support to PHP 8.2/8.1 Docker image

- README.md
- compose/bin/setup-pwa-studio-sampledata
This pull request introduces a script for simplifying the setup process of a Magento 2 environment and configuring PWA Studio. The script automates the installation of sample data for Venia PWA and configures the PWA Studio environment.
This pull request addresses the issues mentioned in [issue](https://github.com/markshust/docker-magento/issues/412).
- Sets up the composer repository for Venia sample data.
- Requires the Venia sample data metapackage.
- Installs Venia sample data modules.
- Reindexes data from the installed modules.
- Checks for the existence of the `.env.dist` file.
- Copies the content of `.env.dist` to `.env` if the file exists.
- Provides a message if the `.env.dist` file is not found.
To utilize the script, provide the Magento 2 base URL as an argument when …
> Added a script that deploys the sample data for PWA

- images/php/8.1/Dockerfile
- images/php/8.2/Dockerfile
- images/php/8.3/Dockerfile
Magento's composer plugin hasn't been updated in over a year, they merged a composer 7 fix but haven't released it... So we'll pin the version for now.
https://github.com/magento/composer-root-update-plugin/issues/40
> Pin Docker Compose v2.6.6

- README.md
- compose/Makefile
- compose/bin/check-dependencies
Introduces a script for the swift and straightforward installation of Magento 2, specifically tailored for beginners. The script provides helpful recommendations for dependencies.
- Simple interface for selecting the Magento 2 version.
- Dependency recommendations tailored to the chosen Magento version.
- Streamlines the installation process, saving time and effort.
> Add check dependencies script

- README.md
Hi, @markshust
I noticed that in this [commit](https://github.com/markshust/docker-magento/commit/8bfb9469ed70671f0b5b115ff3c74b0b15700018) you updated video lesson links to include new Code Quality Tools, but it is shown incorrectly:
This PR fixes the Code Quality Tools list in the `README.md` file.
> Fix video lesson links to include new Code Quality Tools

- compose/compose.dev-linux.yaml
- compose/compose.dev-ssh.yaml
- compose/compose.dev.yaml
- compose/compose.healthcheck.yaml
- compose/compose.yaml
Latest version of docker compose started throwing a **WARN[0000]** notification about `version` being obsolete.
https://github.com/docker/compose/issues/11628
> Removes obsolete `version` directive from docker compose files

- compose/template/dev/tests/integration/etc/install-config-mysql.php.2.4.dist
This pull request updates the Integration testing configuration to use OpenSearch, as we have moved from Elasticsearch to OpenSearch.
> Update Integration testing configuration to use OpenSearch

- compose/bin/setup-ssl
This fixes the case where someone tries to run this setup with a domain name that includes a port number
For example, running `bin/setup magento.test:8443`will cause the certificate to fail with an invalid domain name error, since the port should no be included. However, the port should be used in other parts of `bin/setup domain`
> Fix SSL cert generation when domain has a port included

- compose/bin/n98-magerun2
Description: Update `n98-magerun2` CLI to use a single insert with column names per row. This change will facilitate easier data searching through the dumped database file.
Details: By default, the `mysqldump` command generates `INSERT` query values on new lines, which complicates data searching through the dumped database file.
For example:
```
zgrep -P "VALUES\s*\(.*\d:\d:...*'" database.sql | awk '{print $3}' | uniq
```
Adding the `--human-readable` option to magerun will enforce a single insert with column names per row (equivalent to `--extended-insert=FALSE` in the `mysqldump` command).
Current:
`bin/cli bin/n98-magerun2.phar "$@"`
Proposed change:
`bin/cli bin/n98-magerun2.phar --human-readable "$@"`
> Update n98-magerun2 CLI to use a single insert with column names per row

- compose/bin/mysqldump
- compose/bin/n98-magerun2
Move the option for `mysqldump` to the appropriate file.
Related PR: https://github.com/markshust/docker-magento/pull/1195
> Move the option for mysqldump to the appropriate file

- images/php/8.2/Dockerfile
- images/php/8.3/Dockerfile
PHP >= 8.2.15 removed the FTP extension, but Magento still requests its use for FTP configurations. So, I'm adding it to the Docker PHP 8.2 and 8.3 for new builds and upgrades.
Reference: https://github.com/magento/magento2/issues/39083
> Add PHP FTP ext on Docker setup

- README.md
- images/php/8.1/conf/php-fpm.conf
- images/php/8.2/conf/php-fpm.conf
- images/php/8.3/conf/php-fpm.conf
Correct typos in various configuration and documentation files.
* **PHP-FPM Configuration Files**:
- Correct the typo "adapated" to "adapted" in `images/php/8.1/conf/php-fpm.conf`.
- Correct the typo "adapated" to "adapted" in `images/php/8.2/conf/php-fpm.conf`.
- Correct the typo "adapated" to "adapted" in `images/php/8.3/conf/php-fpm.conf`.
* **README.md**:
- Correct the typo "ratther" to "rather".
> Fix typos in various files

- compose/bin/xdebug
As mentioned in https://github.com/markshust/docker-magento/issues/1189
> Replaces bin/restart by bin/cli kill and removes sleep command

- .github/workflows/build-elasticsearch-7-16.yml
- .github/workflows/build-elasticsearch-8-11.yml
- .github/workflows/build-elasticsearch-8-13.yml
- .github/workflows/build-elasticsearch-8-4.yml
- .github/workflows/build-elasticsearch-8-5.yml
- .github/workflows/build-elasticsearch-8-7.yml
- .github/workflows/build-nginx-1-18.yml
- .github/workflows/build-nginx-1-22.yml
- .github/workflows/build-nginx-1-24.yml
- .github/workflows/build-opensearch-1-2.yml
- .github/workflows/build-opensearch-2-12.yml
- .github/workflows/build-opensearch-2-5.yml
- .github/workflows/build-php-8-1.yml
- .github/workflows/build-php-8-2.yml
- .github/workflows/build-php-8-3.yml
- .github/workflows/build-php-8-4.yml
- .github/workflows/build-rabbitmq-3-11.yml
- .github/workflows/build-rabbitmq-3-12.yml
- .github/workflows/build-rabbitmq-3-13.yml
- .github/workflows/build-rabbitmq-3-8.yml
- .github/workflows/build-rabbitmq-3-9.yml
- .github/workflows/build-ssh.yml
- .github/workflows/shellcheck.yml
Switching the build branch from `master` to `release/next` will allow images to be built using the updated README, images, etc. before pushing the images live. It typically takes a few hours for the builds to complete, so this method will allow me to execute the task to build the images, and calmly continue with other tasks (such as updating the CHANGELOG, etc.) while this happens, also knowing that the `compose.yaml` file will continue to function and not fail during this time.
> Switch GitHub Actions to use release/next branch
