markshust/docker-magento

docker-compose.yml

See https://github.com/mageinferno/magento2-docker-compose/pull/51
This reverts commit c1ca67d6515928156277ed570369fca4c329033b.

Revert "Fixed setup image version, Enterprise installation support"

---

compose/magento-2-windows/bin/copymagento.ps1

Fixes: https://github.com/markoshust/docker-magento/issues/100

Copy Magento into the container does not error anymore

---

compose/magento-2/docker-compose.dev.yml

I added mailhog for development environments, so mails will not send directly to real mail servers.
If you accept this PR, I could edit the README.

add mailhog

---

README.md

Information about virtual memory map requirements.

Documentation for Elasticseach on linux

---

compose/bin/setup
compose/docker-compose.yml

Added RabbitMq support
> To access RabbitMq Management UI - http://localhost:15672

Added rabbitmq support

---

images/php/7.2/conf/php.ini
images/php/7.3/conf/php.ini

@markshust Updated php.ini to avoid few issues.
Reference: 
[magento-cloud/php.ini](https://github.com/magento/magento-cloud/blob/master/php.ini)
[Invalid Form Key. Please refresh the page](https://www.simicart.com/blog/magento-2-invalid-form-key/)

Updated php.ini for php 7.2 and 7.3

---

compose/bin/dev-urn-catalog-generate

Sed manual: `-i[SUFFIX], --in-place[=SUFFIX]`
Remove `misc.xml` from container

Fix dev-urn-catalog-generate

---

README.md
compose/bin/setup-grunt

I follow [Compile LESS using Grunt](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-topics/css_debug.html) to implement it.

Added bin/setup-grunt to instal Grunt configure

---

compose/bin/setup

load db credentials from db.env in setup script similar to mysql script

---

compose/docker-compose.yml

increase mysql max_allowed_packet from 4m to 64m

---

images/nginx/1.18/Dockerfile

@markshust I'm not sure if this should be just an override or should I create a separate dir something like `1.18-alpine` and put a docker file there.
Refs: #244

nginx alpine image

---

compose/bin/download

support for magento 2 enterprise download

---

compose/bin/download

prevent downloading 404 page content if file doesn't exist

---

README.md

Added `--prefer-dist` in composer install command to solve:
1. error on installing from source  `connection reset by peer`
2. speed up the dependencies download.

added --prefer-dist in composer install command

---

images/php/7.3/Dockerfile
images/php/7.4/Dockerfile

Instead of updating the composer version flag regularly there is a flag to keep composer v1.

set composer to latest v1

---

compose/bin/copyfromcontainer
compose/bin/copytocontainer
compose/bin/fixowns

Tested on linux.
Possible fix for #379

Support paths with spaces

---

compose/bin/setup-composer-auth

Fix wrong variable

---

compose/bin/download

Add check if archive is corrupted

---

.github/workflows/shellcheck.yml
compose/bin/cli

Would be good to squash the PR. 
I left the commit to show that it works as expected.

trigger shellcheck only on script file changes

---

compose/bin/download

allow curl to fail download

---

README.md

Added a new shield to showcase this repo's compatibility with Apple Silicon! :)

Added a shield for Apple Silicon support

---

compose/docker-compose.yml
compose/env/elasticsearch.env

fix elasticsearch

---

README.md
compose/bin/stopall

Hi Mark, i added this script to stop all running container, i found it usefull when you switch project and find yourself in the new project directory and cannot start process due to port already used by other running processes.

added script to stop all running container

---

README.md

Correct commands for enabling Redis in README

Correct commands for enabling Redis in README

---

images/nginx/1.18/Dockerfile

Extension to #520: Also configure the user & group id of the nginx user in a similar fashion to avoid permission problems.

Configure nginx user & group id as in FPM image

---

README.md
compose/bin/cli
compose/bin/clinotty
compose/bin/copyfromcontainer
compose/bin/copytocontainer
compose/bin/download
compose/bin/phpcbf
compose/bin/phpcs
compose/bin/phpcs-json-report
compose/bin/redis
compose/bin/remove
compose/bin/root
compose/bin/rootnotty
compose/bin/setup
compose/bin/setup-ssl
compose/bin/setup-ssl-ca
compose/bin/start
compose/bin/status
compose/bin/stop

* Added cli commands for PHP_CodeSniffer

Added cli commands for PHP_CodeSniffer (phpcs & phpcbf)

---

README.md

Hello,
the "maintained?" badge refer to commits activity of another repository.

Changed a badge link that led to another repo

---

README.md

Hi @markshust,
Came across your repository, awesome project! Thanks a lot for creating and sharing.
I found that the mailcatcher hint in the readme was not correct about using port 1080 for sending. For sending it should use port 1025 (have tested that). I also tried to make that sentence be a bit more explanatory (in my best english 🙈).
Last thing I found in this part was the link to the Mageplaza module, the link and the name of the link where in the wrong order.
Thanks!

updates and fixes to the readme about mailcatcher

---

README.md
compose/bin/cli
compose/bin/clinotty
compose/bin/copyfromcontainer
compose/bin/copytocontainer
compose/bin/docker-compose
compose/bin/download
compose/bin/redis
compose/bin/remove
compose/bin/root
compose/bin/rootnotty
compose/bin/setup
compose/bin/setup-ssl
compose/bin/setup-ssl-ca
compose/bin/start
compose/bin/status
compose/bin/stop

`bin/compose` support V1 (`docker-compose`) and V2 (`docker compose`), and also setup custom config file (`docker-compose.yml` and `docker-compose.dev.yml`

Add bin/docker-compose

---

README.md
compose/bin/docker-compose
compose/bin/download
compose/bin/setup
compose/bin/start

Use `docker compose` first, not `docker-compose`
Use `bin/start --no-dev` to replace `bin/docker-compose --no-dev up -d`

Improve bin/docker-compose

---

compose/bin/start

Fix unknown flag: --no-dev issue

---

README.md

relative link for image

---

compose/bin/setup-domain

Small fix for 'web/secure/base_url' being mentioned twice, when it is ssecure and insecure being set

Correct base url in echo

---

compose/bin/magento-version
compose/bin/setup-integration-tests

Get Magento version in 3 methods
- `bin/magento --version`
- `composer.lock`
- `composer.json`

Add bin/magento-version

---

images/php/8.3/Dockerfile

Once the image runs, the imagick directory reminds in the WORKDIR.

Fix imagick directory name

---

README.md
compose/Makefile

This PR adds descriptions for scripts in the `README.md ` and `Makefile` files.
Additionally, I did it by alphabet.

Add descriptions for scripts in the README.md file

---

CHANGELOG.md

This PR fixes the typo in the `CHANGELOG.md` file.

Fix typo in the `CHANGELOG.md` file

---

compose/compose.yaml

Corrected comment typo

---

images/php/8.1/Dockerfile
images/php/8.2/Dockerfile
images/php/8.3/Dockerfile

Hello,
Would you consider adding rsync ?

Add rsync to PHP images for Deployer support

---

compose/compose.yaml

Closes https://github.com/markshust/docker-magento/issues/850

add version tag to mailcatcher image

---

compose/env/elasticsearch.env
compose/env/opensearch.env

Open Search, Elastic Search containers failing due to Java incompatibility with ARM64 chips

---

compose/compose.yaml

Resolves https://github.com/markshust/docker-magento/issues/1320

Add Valkey 8 image for Magento 2.4.8 support #1320

---

compose/compose.yaml

Remove commented-out optimizer flags which do not apply to MySQL
